branch-defaults:
  default:
    environment: django-cloud
    group_suffix: null
global:
  application_name: cloud_app
  branch: null
  default_ec2_keyname: my-key-pair
  default_platform: python2.7
  default_region: us-west-2
  profile: null
  repository: null
  sc: null
